// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	suppliers "github.com/sundowndev/phoneinfoga/v2/lib/remote/suppliers"
)

// DehashedSupplier is an autogenerated mock type for the DehashedSupplierInterface type
type DehashedSupplier struct {
	mock.Mock
}

// SearchByPhone provides a mock function with given fields: _a0, _a1, _a2
func (_m *DehashedSupplier) SearchByPhone(_a0 string, _a1 string, _a2 string) (*suppliers.DehashedResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *suppliers.DehashedResponse
	if rf, ok := ret.Get(0).(func(string, string, string) *suppliers.DehashedResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*suppliers.DehashedResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
