// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	suppliers "github.com/sundowndev/phoneinfoga/v2/lib/remote/suppliers"
)

// IPQSSupplier is an autogenerated mock type for the IPQSSupplierInterface type
type IPQSSupplier struct {
	mock.Mock
}

// Validate provides a mock function with given fields: _a0, _a1
func (_m *IPQSSupplier) Validate(_a0 string, _a1 string) (*suppliers.IPQSValidateResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *suppliers.IPQSValidateResponse
	if rf, ok := ret.Get(0).(func(string, string) *suppliers.IPQSValidateResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*suppliers.IPQSValidateResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
