// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	suppliers "github.com/sundowndev/phoneinfoga/v2/lib/remote/suppliers"
)

// NumberingPlanSupplier is an autogenerated mock type for the NumberingPlanSupplierInterface type
type NumberingPlanSupplier struct {
	mock.Mock
}

// Lookup provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *NumberingPlanSupplier) Lookup(_a0 string, _a1 string, _a2 string, _a3 string) (*suppliers.NumberingPlanResult, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 *suppliers.NumberingPlanResult
	if rf, ok := ret.Get(0).(func(string, string, string, string) *suppliers.NumberingPlanResult); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*suppliers.NumberingPlanResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
