// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	suppliers "github.com/sundowndev/phoneinfoga/v2/lib/remote/suppliers"
)

// SearchBackend is an autogenerated mock type for the SearchBackendInterface type
type SearchBackend struct {
	mock.Mock
}

// Search provides a mock function with given fields: _a0, _a1, _a2
func (_m *SearchBackend) Search(_a0 string, _a1 string, _a2 string) (int, []suppliers.SearchResultItem, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string, string) int); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 []suppliers.SearchResultItem
	if rf, ok := ret.Get(1).(func(string, string, string) []suppliers.SearchResultItem); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]suppliers.SearchResultItem)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string, string) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
