// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	suppliers "github.com/sundowndev/phoneinfoga/v2/lib/remote/suppliers"
)

// ValidationProvider is an autogenerated mock type for the ValidationProvider type
type ValidationProvider struct {
	mock.Mock
}

// Name provides a mock function with given fields:
func (_m *ValidationProvider) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// KeyEnvVar provides a mock function with given fields:
func (_m *ValidationProvider) KeyEnvVar() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Validate provides a mock function with given fields: _a0, _a1
func (_m *ValidationProvider) Validate(_a0 string, _a1 string) (*suppliers.ValidationResult, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *suppliers.ValidationResult
	if rf, ok := ret.Get(0).(func(string, string) *suppliers.ValidationResult); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*suppliers.ValidationResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
